{{- if .Values.secret.jwt }}
{{- if not .Values.secret.jwt.secretRef }}
{{- if not .Values.secret.jwt.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.jwt" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  anonKey:    {{ .Values.secret.jwt.anonKey    | b64enc }}
  serviceKey: {{ .Values.secret.jwt.serviceKey | b64enc }}
  secret:     {{ .Values.secret.jwt.secret     | b64enc }}
{{- end }}
{{- end }}
{{- end }}
