{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ include "supabase.fullname" . }}-db-supabase
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  name: _supabase
  owner: supabase_admin
  cluster:
    name: {{ .Values.cnpg.clusterName }}
  schemas:
    - name: _analytics
      owner: supabase_admin
      ensure: present
    - name: _supavisor
      owner: supabase_admin
      ensure: present
{{- end }}
