#!/usr/bin/env bash
# Fetches the supabase/postgres DB bootstrap SQL for a given release tag and
# writes two concatenated files under the chart:
#   files/db/init.sql        <- contents of migrations/db/init-scripts/
#   files/db/migrations.sql  <- contents of migrations/db/migrations/
#
# CNPG bootstrap does not invoke the supabase/postgres image's docker
# entrypoint, so these scripts would otherwise never run. Helm loads both
# files into the initdb ConfigMap via .Files.Get and CNPG replays them
# through postInitSQLRefs.
#
# Usage (from anywhere):
#   ./scripts/fetch-db-init.sh            # uses Chart.yaml appVersion
#   ./scripts/fetch-db-init.sh 17.6.1.108
#
# Requires: curl, python3 (stdlib json only).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CHART_DIR="$REPO_ROOT/charts/supabase"
OUT_DIR="$CHART_DIR/files/db"

# Migrations that break the CNPG deployment and must not be replayed.
# 10000000000000_demote-postgres: strips the `postgres` role of SUPERUSER /
#   BYPASSRLS; CNPG uses that very role as the app superuser and the operator
#   can no longer reconcile managed.roles/backups after it runs.
# *_pgbouncer*: reference a `pgbouncer` schema that the supabase/postgres
#   image pre-creates out-of-band; we do not ship that setup, so the
#   migrations fail with `schema "pgbouncer" does not exist`.
SKIP_MIGRATIONS=(
  "10000000000000_demote-postgres.sql"
  "20250312095419_pgbouncer_ownership.sql"
  "20250417190610_update_pgbouncer_get_auth.sql"
  "20251121132723_correct_search_path_pgbouncer.sql"
)

TAG="${1:-}"
if [[ -z "$TAG" ]]; then
  TAG="$(awk '/^appVersion:/ {gsub(/"/,"",$2); print $2}' "$CHART_DIR/Chart.yaml")"
fi
if [[ -z "$TAG" ]]; then
  echo "ERROR: could not resolve tag (pass one, or set Chart.yaml appVersion)" >&2
  exit 2
fi

API_BASE="https://api.github.com/repos/supabase/postgres/contents/migrations/db"
RAW_BASE="https://raw.githubusercontent.com/supabase/postgres/${TAG}/migrations/db"

echo "Fetching supabase/postgres DB bootstrap for tag: ${TAG}"
mkdir -p "$OUT_DIR"

should_skip() {
  local name="$1" skip
  for skip in "${SKIP_MIGRATIONS[@]}"; do
    [[ "$name" == "$skip" ]] && return 0
  done
  return 1
}

list_files() {
  local subdir="$1"
  curl -fsSL "${API_BASE}/${subdir}?ref=${TAG}" \
    | python3 -c 'import sys, json
for entry in json.load(sys.stdin):
    if entry["type"] == "file" and entry["name"].endswith(".sql"):
        print(entry["name"])' \
    | sort
}

build_file() {
  local subdir="$1" out="$2"
  echo "  -> ${subdir} => ${out}"
  local files
  files="$(list_files "$subdir")"
  if [[ -z "$files" ]]; then
    echo "     (no .sql files found — aborting)" >&2
    exit 1
  fi

  {
    printf -- '-- AUTOGENERATED by supabase/scripts/fetch-db-init.sh\n'
    printf -- '-- source: github.com/supabase/postgres @ %s (migrations/db/%s)\n' "$TAG" "$subdir"
    printf -- '-- DO NOT EDIT by hand — rerun the script to refresh.\n'
  } > "$out"

  while read -r f; do
    [[ -z "$f" ]] && continue
    if should_skip "$f"; then
      echo "     SKIP ${f}"
      continue
    fi
    echo "     ${f}"
    {
      printf -- '\n-- ============================================================\n'
      printf -- '-- %s/%s\n' "$subdir" "$f"
      printf -- '-- ============================================================\n'
      curl -fsSL "${RAW_BASE}/${subdir}/${f}"
      printf '\n'
    } >> "$out"
  done <<< "$files"

  local bytes
  bytes="$(wc -c < "$out")"
  echo "     ${bytes} bytes"
  # ConfigMap key limit is 1 MiB; warn well before we'd hit it.
  if (( bytes > 900000 )); then
    echo "WARNING: ${out} is ${bytes} bytes, approaching 1 MiB ConfigMap limit." >&2
  fi
}

build_file init-scripts "$OUT_DIR/init.sql"
build_file migrations   "$OUT_DIR/migrations.sql"
